### ISSUE TITLE
Can't mass-assign protected attributes for Attachinary

### ISSUE THREAD

**Issue by xrimpy** [assembler/attachinary#96] opened 2014-09-09 18:07 UTC
Can't mass-assign protected attributes for Attachinary::File: public_id, version, width, height, format, resource_type

My model

class Vendor < ActiveRecord::Base
  has_attachment :coverimage 
  attr_accessible :coverimage
end

The file is being uploaded to Cloudinary

**Comment by coreyward** [comment] 2015-04-27 19:29
This is a duplicate of #88.

**Closed** 2021-06-21 03:17 UTC
